# Generated by Django 6.0.2 on 2026-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='staffId',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
