# Generated by Django 6.0.2 on 2026-03-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_designation_servicestaff_name_and_more'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='staffId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicestaff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='vehicleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
        migrations.AlterModelTable(
            name='servicedetail',
            table=None,
        ),
    ]
