# Generated by Django 6.0.2 on 2026-04-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_servicedetail_staffid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdetails',
            name='parking_slot',
        ),
    ]
