# Generated by Django 6.0.2 on 2026-03-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_servicedetail_service_photo_servicedetail_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='vehicleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
    ]
