# Generated by Django 6.0.2 on 2026-03-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_transportation_vehicleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
