# Generated by Django 6.0.2 on 2026-04-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_parkingdetails_parking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
