# Generated by Django 6.0.2 on 2026-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_vehicle_vehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle/'),
        ),
    ]
