# Generated by Django 6.0.2 on 2026-03-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admin_servicestaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestaff',
            old_name='designation',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='servicestaff',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='servicestaff',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='servicestaff',
            name='userId',
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='servicestaff',
            table=None,
        ),
    ]
