# Generated by Django 6.0.2 on 2026-03-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_designation_servicestaff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestaff',
            name='phone',
        ),
    ]
